### PR TITLE
Change how we count Paypal transactions

### PR DESCRIPTION
**Pull request by jbuck**

### CODE REVIEW

**Comment by jbuck** [comment]
@adamlofting Here is a current data set from the transaction db:

```
transactions=> select type, status, sum(amount) from paypal where timestamp >= '2015-10-04' group by type, status order by sum;
             type             |       status       |     sum
------------------------------+--------------------+--------------
 Transfer                     | Completed          | -$198,019.77
 Temporary Hold               | Removed            |  -$51,082.76
 Currency Conversion (debit)  | Completed          |  -$39,955.82
 Temporary Hold               | Placed             |   -$6,896.93
 Refund                       | Completed          |     -$380.00
 Reversal                     | Completed          |      -$21.00
 Recover                      | Completed          |      -$10.00
 Authorization                | Pending            |        $0.05
 Donation                     | Cleared            |        $3.00
 Payment                      | Reversed           |        $3.00
 Donation                     | Uncleared          |        $5.00
 Donation                     | Reversed           |       $10.00
 Fee Reversal                 | Completed          |       $12.41
 Payment                      | Uncleared          |       $20.00
 Payment                      | Held               |       $27.00
 Payment                      | Pending            |       $58.00
 Payment                      | Cleared            |       $62.00
 Donation                     | Pending            |      $123.00
 Donation                     | Canceled           |      $149.00
 Payment                      | Partially Refunded |      $180.00
 Payment                      | Refunded           |      $245.00
 Currency Conversion (credit) | Completed          |   $37,598.92
 Payment                      | Completed          |  $130,754.63
 Donation                     | Completed          |  $135,270.25
```

Based on this, I think this patch is a more accurate way of counting a value for the totalizer. Would you change it?

**Comment by adamlofting** [comment]
@jbuck - I can't find good docs on what the `Temporary Hold` type is referring to. Do you have any more info on that? 

Also, I think `type IN (...` needs to include:
- `Refund`
- `Reversal`
- `Recover`
- `Fee Reversal`

...to removed refunded and spam donations from the total, as the original success transactions will still exist in the `Completed` records

**Comment by jbuck** [comment]
Temporary Hold is our credit card fraud victims getting their money back! Hooray fraud :tada:

**Comment by jbuck** [comment]
Okay, updated the patch. I didn't include the Fee Reversal because we don't count the Paypal fees when counting money towards the totalizer, and we've only ever had $20 in Recover transactions.

**Comment by jbuck** [comment]
Now that we're tracking USD amounts:

```
transactions=> select type, status, sum(amount) amount, sum(settle_amount) settle_amount 
from paypal where timestamp >= '2015-10-04' and amount != '0' group by type, status
order by amount;
             type             |       status       |    amount    | settle_amount
------------------------------+--------------------+--------------+---------------
 Transfer                     | Completed          | -$198,019.77 |
 Temporary Hold               | Removed            |  -$51,082.76 |   -$51,082.76
 Currency Conversion (debit)  | Completed          |  -$43,566.25 |
 Temporary Hold               | Placed             |   -$6,896.93 |    -$6,896.93
 Refund                       | Completed          |     -$380.00 |      -$248.66
 Reversal                     | Completed          |      -$21.00 |       -$21.00
 Recover                      | Completed          |      -$10.00 |
 Authorization                | Pending            |        $0.05 |         $0.05
 Payment                      | Reversed           |        $3.00 |         $3.00
 Donation                     | Cleared            |        $8.00 |         $8.00
 Donation                     | Reversed           |       $10.00 |        $10.00
 Fee Reversal                 | Completed          |       $12.41 |
 Payment                      | Uncleared          |       $20.00 |        $20.00
 Payment                      | Held               |       $47.00 |        $47.00
 Payment                      | Cleared            |       $62.00 |        $62.00
 Payment                      | Pending            |       $78.00 |        $78.00
 Donation                     | Pending            |      $123.00 |       $123.00
 Donation                     | Canceled           |      $149.00 |       $149.00
 Payment                      | Partially Refunded |      $180.00 |       $265.71
 Payment                      | Refunded           |      $245.00 |       $356.85
 Currency Conversion (credit) | Completed          |   $41,367.77 |
 Payment                      | Completed          |  $135,861.63 |   $141,953.60
 Donation                     | Completed          |  $137,053.25 |   $128,162.33
```

**Comment by jbuck** [comment]
Before I can add other categories to the totalizer amount I need to accurately calculate them, so I'm going to exclude them for now.

**Pull request merged**
